name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MPI: [ON, OFF]
        PETSC: [ON, OFF]
        CXX: [g++, clang++]
      exclude:
        - MPI: OFF
          PETSC: ON
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libeigen3-dev libxml2-dev petsc-dev libboost-all-dev python-dev python-numpy
      - uses: actions/checkout@v1
      - name: Generate build directory
        run: mkdir -p build
      - name: Configure
        working-directory: build
        env:
          CXX: ${{ matrix.CXX }}
        run: cmake -DBUILD_SHARED_LIBS=ON -DMPI=${{ matrix.MPI }} -DPETSC=${{ matrix.PETSC }} ..
      - name: Compile
        working-directory: build
        run: make -j $(nproc)
      - name: Test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: build
        run: make test
