name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ format('{0} {1} {2}', matrix.CXX, matrix.MPI, matrix.PETSC) }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MPI: [MPI, NoMPI]
        PETSC: [PETSC, NoPETSC]
        CXX: [g++, clang++]
        exclude:
          - MPI: NoMPI
            PETSC: PETSC
    env:
      CCACHE_DIR: ${{ workspace }}/ccache

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libeigen3-dev libxml2-dev petsc-dev libboost-all-dev python-dev python-numpy ccache
      - name: Restore ccache
        uses: actions/cache@v1
        with:
          path: ${{ workspace }}/ccache
          key: ${{ github.repository }}-${{ runner.OS }}-ccache-${{ matrix.CXX }}-${{ matrix.MPI }}-${{ matrix.PETSC }}
      - uses: actions/checkout@v1
      - name: Generate build directory
        run: mkdir -p build
      - name: Configure
        working-directory: build
        env:
          CXX: ${{ matrix.CXX }}
          CXX_FLAGS: "-Wall -Wextra -Wpedantic"
        run: cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug -DMPI=${{ matrix.MPI == 'MPI' }} -DPETSC=${{ matrix.PETSC == 'PETSC' }} -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ..
      - name: Compile
        working-directory: build
        run: make -j $(nproc)
      - name: Tests - mandatory
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: build
        run: ctest -LE canfail
      - name: Tests - canfail
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: build
        continue-on-error: true
        run: ctest -L canfail
