name: "Release Dockerfile"
on:
  release:
    types: [published, released]
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        env:
          version: ${{ github.events.release.tag_name }}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          dockerfile: "./tools/releasing/packaging/docker/Dockerfile"
          repository: precice/precice
          tags: ${{ env.version }},latest
          build-args: |
            version=${{ env.version }}
